"""Quality-gate minimums for property and migration test suites."""

STANDARD_PBT_MIN_EXAMPLES = 100
SERIALIZER_MIN_EXAMPLES = STANDARD_PBT_MIN_EXAMPLES
CONCURRENCY_MIN_EXAMPLES = 50
CONCURRENCY_MIN_OPERATIONS = 2
CONCURRENCY_CI_MAX_OPERATIONS = 32
CONCURRENCY_EXTENDED_MAX_OPERATIONS = 100

LOCAL_PROFILE = "local"
CI_PROFILE = "ci"
CONCURRENCY_PROFILE = "concurrency"
CONCURRENCY_EXTENDED_PROFILE = "extended"
CONCURRENCY_EXTENDED_PROFILE_ALIASES = frozenset(
    {CONCURRENCY_EXTENDED_PROFILE, "concurrency-extended"}
)

HYPOTHESIS_PROFILE_MIN_EXAMPLES = {
    LOCAL_PROFILE: STANDARD_PBT_MIN_EXAMPLES,
    CI_PROFILE: STANDARD_PBT_MIN_EXAMPLES,
    CONCURRENCY_PROFILE: CONCURRENCY_MIN_EXAMPLES,
    CONCURRENCY_EXTENDED_PROFILE: STANDARD_PBT_MIN_EXAMPLES,
    "concurrency-extended": STANDARD_PBT_MIN_EXAMPLES,
}

DETERMINISTIC_HYPOTHESIS_SETTINGS = {
    "deadline": None,
    "derandomize": True,
    "database": None,
}


def concurrency_max_operations(profile_name: str) -> int:
    """Return the generated feedback-batch ceiling for a named profile."""
    if profile_name in CONCURRENCY_EXTENDED_PROFILE_ALIASES:
        return CONCURRENCY_EXTENDED_MAX_OPERATIONS
    return CONCURRENCY_CI_MAX_OPERATIONS
